### PR TITLE
update compile instructions

### LINKED ISSUE #442: Installation problems on centos linux system
I am working on a CentOS Linux release 8.5.2111 system, am following the [Linux documentation](https://indigo-dc.gitbook.io/oidc-agent/installation/install) and have installed all the build dependencies (apart from devscripts, which doesn't work). 

I have additionally compiled all the packages for which I get errors related to the requirements in the '.h' files within multiple src/ subdirectories (eg. envchain, libsodium, etc..). However, I am stuck on this one: JavaScriptCore/JavaScript.h. Here the error. 
```
In file included from src/oidc-prompt/webview.cc:3:
src/oidc-prompt/webview.h:445:10: fatal error: JavaScriptCore/JavaScript.h: No such file or directory
 #include <JavaScriptCore/JavaScript.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:425: obj/oidc-prompt/webview.o] Error 1
```

### PR DESCRIPTION
**Pull request by marcvs**
Closes #442

### CODE REVIEW

File: gitbook/installation/install.md [hunk 1]
```diff
@@ -24,15 +24,18 @@ If you want to build oidc-agent from source you can do so.
...
+- libqrencode (libqrencode-dev)
 - [libcurl](https://curl.haxx.se/libcurl/) (libcurl4-openssl-dev)
 - [libsodium (>= 1.0.14)](https://download.libsodium.org/doc/) (libsodium-dev)
 - [libmicrohttpd](https://www.gnu.org/software/libmicrohttpd/) (libmicrohttpd-dev)
+- help2man
 - libsecret (libsecret-1-dev)
-- libqrencode (libqrencode-dev)
-- gtk3 (libgtk-3-dev)
-- webkit2-gtk (libwebkit2gtk-4.0-dev)
+- desktop-file-utils
```
Comment (zachmann) [inline gitbook/installation/install.md:35]: Why should this be needed?

File: gitbook/installation/install.md [hunk 2]
```diff
@@ -24,15 +24,18 @@ If you want to build oidc-agent from source you can do so.
...
+- qrencode-devel
```
Comment (zachmann) [inline gitbook/installation/install.md:36]: This is just the rpm version of libqrencode-dev listed above.

We generally list here only the debian names

File: gitbook/installation/install.md [hunk 3]
```diff
@@ -24,15 +24,18 @@ If you want to build oidc-agent from source you can do so.
...
 - make
+- gcc
+- libqrencode (libqrencode-dev)
 - [libcurl](https://curl.haxx.se/libcurl/) (libcurl4-openssl-dev)
 - [libsodium (>= 1.0.14)](https://download.libsodium.org/doc/) (libsodium-dev)
 - [libmicrohttpd](https://www.gnu.org/software/libmicrohttpd/) (libmicrohttpd-dev)
+- help2man
 - libsecret (libsecret-1-dev)
-- libqrencode (libqrencode-dev)
-- gtk3 (libgtk-3-dev)
```
Comment (zachmann) [inline gitbook/installation/install.md:34]: gtk3 is still needed

File: gitbook/installation/install.md [hunk 4]
```diff
@@ -24,15 +24,18 @@ If you want to build oidc-agent from source you can do so.
...
-- webkit2-gtk (libwebkit2gtk-4.0-dev)
```
Comment (zachmann) [inline gitbook/installation/install.md:35]: this is also needed.
You add something else instead below (rpm version), but this one is the debian name.

**Review by zachmann — CHANGES_REQUESTED** [review]
Please don't mix debian style names with rpms.

The way it currently is, we only mention debian names and users have to find the rpms themself.
If you want you can add a separate section for rpms. But it should be clear.
