### ISSUE TITLE
Installation problems on centos linux system 

### ISSUE THREAD

**Issue by egazzarr** [indigo-dc/oidc-agent#442]
I am working on a CentOS Linux release 8.5.2111 system, am following the [Linux documentation](https://indigo-dc.gitbook.io/oidc-agent/installation/install) and have installed all the build dependencies (apart from devscripts, which doesn't work). 

I have additionally compiled all the packages for which I get errors related to the requirements in the '.h' files within multiple src/ subdirectories (eg. envchain, libsodium, etc..). However, I am stuck on this one: JavaScriptCore/JavaScript.h. Here the error. 
```
In file included from src/oidc-prompt/webview.cc:3:
src/oidc-prompt/webview.h:445:10: fatal error: JavaScriptCore/JavaScript.h: No such file or directory
 #include <JavaScriptCore/JavaScript.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:425: obj/oidc-prompt/webview.o] Error 1
```

**Comment by marcvs** [comment]
Hi There,

we had some changes in the build environment. Please try with installing these packages:
```
make
gcc >= 4.8
libcurl-devel >= 7.29
libsodium-devel >= 1.0.16
libmicrohttpd-devel >= 0.9.33
help2man >= 1.41
libsecret-devel >= 0.18.4
desktop-file-utils
qrencode-devel >= 3
webkitgtk4-devel
```
If it works I'll update the docs asap.

**Comment by zachmann** [comment]
Is there a need for manual building? 
We provide releases for many distributions (also Centos8) at http://repo.data.kit.edu/

For building:
As Marcus just commented there where some changes, and we forgot to update the instructions.
The missing package is most likely `webkitgtk4-devel`

**Comment by egazzarr** [comment]
Hi both, thanks for the useful input, I installed webkitgtk4-devel and finally I am able to use the oidc-agent command line.  
I would maybe make the instructions @zachmann provided at http://repo.data.kit.edu/ a bit easier to follow and wordy, would have made the installation process more pleasurable, in my opinion. 
Cheers!

**Comment by marcvs** [comment]
Well. This repo is more for our development. We're working on getting the packages into epel ;)

**Comment by marcvs** [comment]
I've also updated the instructions at https://repo.data.kit.edu
